apiVersion: v1
kind: Pod
metadata:
  name: lazykube-ci
  labels:
    ci: k8s
spec:
  nodeSelector:
    ci: k8s
  containers:
  - name: lazykube
    image: lyanchih/lazykube
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
    tty: true
    env:
    - name: DEBIAN_FRONTEND
      value: noninteractive
    - name: DOCKER_HOST
      value: 127.0.0.1
    - name: LIBVIRT_DEFAULT_URI
      value: qemu+unix:///system?socket=/var/run/libvirt/libvirt-sock
    - name: FIRST_BRIDGE
      value: vm0
    - name: DOCKER_HOST_INTERFACE
      value: net0
    volumeMounts:
    - name: sshkey
      mountPath: /root/.ssh
    - name: lazykube
      mountPath: /src
    - name: run
      mountPath: /var/run
    - name: lazykube-conf
      mountPath: /etc/lazykube
  - name: dind
    image: docker:dind
    args:
    - --mtu
    - "1400"
    securityContext:
      privileged: true
    volumeMounts:
    - name: lazykube
      mountPath: /src
  volumes:
  - name: sshkey
    hostPath:
      path: /data/.ssh
  - name: run
    hostPath:
      path: /var/run
  - name: lazykube
    emptyDir: {}
  - name: lazykube-conf
    configMap:
      name: lazykube-conf